// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v5.26.1
// source: infogain_model.pb

package infogainpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// InfoGainModel 存储信息增益模型的相关参数
type InfoGainModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	MaxFeatures int32              `protobuf:"varint,1,opt,name=max_features,json=maxFeatures,proto3" json:"max_features,omitempty"`
	Scores      map[string]float64 `protobuf:"bytes,2,rep,name=scores,proto3" json:"scores,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"fixed64,2,opt,name=value,proto3"` // scores 的 key 就是特征词
	NumFeatures int32              `protobuf:"varint,3,opt,name=num_features,json=numFeatures,proto3" json:"num_features,omitempty"`
}

func (x *InfoGainModel) Reset() {
	*x = InfoGainModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_infogain_model_pb_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InfoGainModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InfoGainModel) ProtoMessage() {}

func (x *InfoGainModel) ProtoReflect() protoreflect.Message {
	mi := &file_infogain_model_pb_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InfoGainModel.ProtoReflect.Descriptor instead.
func (*InfoGainModel) Descriptor() ([]byte, []int) {
	return file_infogain_model_pb_rawDescGZIP(), []int{0}
}

func (x *InfoGainModel) GetMaxFeatures() int32 {
	if x != nil {
		return x.MaxFeatures
	}
	return 0
}

func (x *InfoGainModel) GetScores() map[string]float64 {
	if x != nil {
		return x.Scores
	}
	return nil
}

func (x *InfoGainModel) GetNumFeatures() int32 {
	if x != nil {
		return x.NumFeatures
	}
	return 0
}

var File_infogain_model_pb protoreflect.FileDescriptor

var file_infogain_model_pb_rawDesc = []byte{
	0x0a, 0x11, 0x69, 0x6e, 0x66, 0x6f, 0x67, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c,
	0x2e, 0x70, 0x62, 0x12, 0x0e, 0x69, 0x6e, 0x66, 0x6f, 0x67, 0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f,
	0x64, 0x65, 0x6c, 0x22, 0xd3, 0x01, 0x0a, 0x0d, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x61, 0x69, 0x6e,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x12, 0x21, 0x0a, 0x0c, 0x6d, 0x61, 0x78, 0x5f, 0x66, 0x65, 0x61,
	0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x0b, 0x6d, 0x61, 0x78,
	0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x12, 0x41, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x72,
	0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x29, 0x2e, 0x69, 0x6e, 0x66, 0x6f, 0x67,
	0x61, 0x69, 0x6e, 0x5f, 0x6d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x49, 0x6e, 0x66, 0x6f, 0x47, 0x61,
	0x69, 0x6e, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x2e, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e,
	0x74, 0x72, 0x79, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x12, 0x21, 0x0a, 0x0c, 0x6e,
	0x75, 0x6d, 0x5f, 0x66, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x05, 0x52, 0x0b, 0x6e, 0x75, 0x6d, 0x46, 0x65, 0x61, 0x74, 0x75, 0x72, 0x65, 0x73, 0x1a, 0x39,
	0x0a, 0x0b, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x73, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x10, 0x0a,
	0x03, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x6b, 0x65, 0x79, 0x12,
	0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05,
	0x76, 0x61, 0x6c, 0x75, 0x65, 0x3a, 0x02, 0x38, 0x01, 0x42, 0x0f, 0x5a, 0x0d, 0x2e, 0x2f, 0x3b,
	0x69, 0x6e, 0x66, 0x6f, 0x67, 0x61, 0x69, 0x6e, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x33,
}

var (
	file_infogain_model_pb_rawDescOnce sync.Once
	file_infogain_model_pb_rawDescData = file_infogain_model_pb_rawDesc
)

func file_infogain_model_pb_rawDescGZIP() []byte {
	file_infogain_model_pb_rawDescOnce.Do(func() {
		file_infogain_model_pb_rawDescData = protoimpl.X.CompressGZIP(file_infogain_model_pb_rawDescData)
	})
	return file_infogain_model_pb_rawDescData
}

var file_infogain_model_pb_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_infogain_model_pb_goTypes = []interface{}{
	(*InfoGainModel)(nil), // 0: infogain_model.InfoGainModel
	nil,                   // 1: infogain_model.InfoGainModel.ScoresEntry
}
var file_infogain_model_pb_depIdxs = []int32{
	1, // 0: infogain_model.InfoGainModel.scores:type_name -> infogain_model.InfoGainModel.ScoresEntry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_infogain_model_pb_init() }
func file_infogain_model_pb_init() {
	if File_infogain_model_pb != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_infogain_model_pb_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InfoGainModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_infogain_model_pb_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_infogain_model_pb_goTypes,
		DependencyIndexes: file_infogain_model_pb_depIdxs,
		MessageInfos:      file_infogain_model_pb_msgTypes,
	}.Build()
	File_infogain_model_pb = out.File
	file_infogain_model_pb_rawDesc = nil
	file_infogain_model_pb_goTypes = nil
	file_infogain_model_pb_depIdxs = nil
}
